### ISSUE TITLE
[MATLAB] Need data indexing features

### ISSUE THREAD

**Issue by albertchai01** [ucsd-lo-group/social-network-analysis#6]
Needs data indexing features in code
Development in progress

**Comment by albertchai01** [comment]
For easier code execution, create .p file for stable releases. However, both .p and .m code will be published.
https://www.mathworks.com/help/matlab/matlab_prog/protect-your-source-code.html

**Comment by Alee4738** [comment]
What do you mean by data indexing features? What is it you'd like to do?

**Comment by Alee4738** [comment]
See my commit "Implement master, write to csv, add header". It should've solved the issue.
