### ISSUE TITLE
[ALL] Add version code to all code

### ISSUE THREAD

**Issue by smlo** [ucsd-lo-group/social-network-analysis#8]
Add version of the code to the prints out and introduction text

**Comment by albertchai01** [comment]
Script version added to R code with the following declaration:
For the console initial run:
`cat("Current Script Engine Version Build: 0.4-beta-103017")`
For the text file print out as .txt file, after Summary Heading: 
`cat("Current Script Engine Version Build: ", scriptversionRead, "\n")`

Still require declaration in MATLAB code, IP

**Comment by albertchai01** [comment]
MATLAB code will not likely be heavily modified in this current release. Only R code will continue to be modified more heavily to adapt to changes needed. R code currently contains these version trackers.
